apiVersion: v1
kind: Service
metadata:
  name: go-web-app
spec:
<<<<<<< HEAD
  type: ClusterIP
=======
  type: ClusterIP
>>>>>>> c81e2d519df910bedf09d006d1ac1cb540ffdaab
  selector:
    app: go-web-app
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
